### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by mzbqhbc** [leo0123456/Smart-camera#1]
```
    from util.generator_model import Generator
ModuleNotFoundError: No module named 'util'
```
请问这个 util库是什么库呀？ 怎么装呢？

**Comment by leo0123456** [comment]
你先百度一下解决，解决不了的话，我再看看，这个项目太早了都忘了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leo0123456/Smart-camera"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 晚上8:27
收件人:&nbsp;"leo0123456/Smart-camera"<Smart-camera@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[leo0123456/Smart-camera] util (#1)





     from util.generator_model import Generator ModuleNotFoundError: No module named 'util'  
请问这个 util库是什么库呀？ 怎么装呢？

**Comment by leo0123456** [comment]
GitHub上面那个不太完整，主要是整个项目附带的文件太大了，我只上传了一部分，你想要完整的项目还有当时写的结课文档&nbsp; &nbsp;+qq 1064603765




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leo0123456/Smart-camera"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 晚上8:27
收件人:&nbsp;"leo0123456/Smart-camera"<Smart-camera@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[leo0123456/Smart-camera] util (#1)





     from util.generator_model import Generator ModuleNotFoundError: No module named 'util'  
请问这个 util库是什么库呀？ 怎么装呢？

**Comment by mzbqhbc** [comment]
算了  我已经放弃这个项目 自己写了  谢谢回复
